name: Teste acao oficial

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  usa-oficial:
    runs-on: ubuntu-latest
    steps:
      - name: Baixa o codigo com acao oficial do GitHub
        uses: actions/checkout@v4
      - run: echo "checkout ok"
