name: Teste terceiro por codigo exato

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  usa-terceiro-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Acao de terceiro fixada por codigo exato
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: false
      - run: echo "chegou ao fim"
